### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by OlgaRadDev** [OlgaRadDev/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Collaborator-bsa20** [comment]
https://www.donaldjtrump.com/get-involved/sms
https://www.facebook.com/DonaldTrump/
https://twitter.com/realDonaldTrump
https://www.instagram.com/realdonaldtrump/
https://www.youtube.com/channel/UCAql2DyGU2un1Ei2nMYsqOA

**Comment by Collaborator-bsa20** [comment]
Achievement

According to the latest Forbes' world ranking of billionaires, Trump has an estimated fortune of $3.1 billion, mostly earned on the back of property, making him the 766th richest person in the world. On top of this, he has had a successful career in reality TV, having starred in the U.S. version of The Apprentice, and he confounded the world by winning the U.S. presidential election in 2016. As far as high-achievers go, it’s hard to think of anyone else on Earth who has had a more successful career if you measure success on the basis of fame, money and power. 

Authenticity

Trump is an authentic leader in the way most people define authenticity – he means what he says and he will say what he means, even if it is utterly unpalatable to the people who are listening to him. Despite the fashion for so-called authenticity, the reality is that we live in a hugely inauthentic world. Companies spend fortunes on PRs, marketers and brand consultants to paint themselves in the best possible light. 

Collaboration

“America first,” Trump’s campaign slogan, says it all. He’s not much of a collaborator, especially on the international stage. His disagreements with fellow world leaders Angela Merkel and Justin Trudeau are well publicized. He has imposed trade tariffs on China and the EU. He’s publicly scolded NATO’s European members for not pulling their weight with defense spending. And he’s pulled the U.S. out of the Paris climate accord and the North American Free Trade Agreement.

Ownership

The issue with Trump is not so much that he himself doesn’t take ownership – since he clearly does. It’s more the case that he doesn’t seem to let anyone else take it as well. Despite criticizing his predecessor, Barack Obama, for his use of executive orders, Trump signed more executive orders in his first 100 days than any president since World War II. He’s also distanced himself from advisers who don’t share his point of view.

Vision

No one could say that Trump lacks a vision – his vision is “America First.” What does that mean in practice? It means jobs for Americans, a smaller U.S. trade deficit, a crackdown on illegal immigration and the end of freeloading European nations achieving their military security at the expense of the US defense budget. Today, we’ve all got a pretty good idea of what President Trump’s vision is, which, in some ways, is testament to his strength in articulating it. Arguably, however, there are some notable flaws in the strategy that he is using to achieve his vision – in particular, the trade tariffs, which already appear to be having unintended consequences at home, and some wildly unpopular immigration policies that have damaged his standing abroad.
